// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ob59Xbd_yP-611IY_xkdMRsByfIu7Lg',
    appId: '1:88495146273:web:f319ab85434d00c214aa60',
    messagingSenderId: '88495146273',
    projectId: 'proyectof-ebd97',
    authDomain: 'proyectof-ebd97.firebaseapp.com',
    databaseURL: 'https://proyectof-ebd97-default-rtdb.firebaseio.com',
    storageBucket: 'proyectof-ebd97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv6uOdCnfU6ucfw1yaNd3nQYD8nbxQTzw',
    appId: '1:88495146273:android:9640e3bdf726155914aa60',
    messagingSenderId: '88495146273',
    projectId: 'proyectof-ebd97',
    databaseURL: 'https://proyectof-ebd97-default-rtdb.firebaseio.com',
    storageBucket: 'proyectof-ebd97.appspot.com',
  );

}